// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1m5jKBIa9Svz8PQgMcOpWf_KGMM1k2GI',
    appId: '1:39167277239:web:273b24fa8ff252fecbb532',
    messagingSenderId: '39167277239',
    projectId: 'song-app-55d7b',
    authDomain: 'song-app-55d7b.firebaseapp.com',
    storageBucket: 'song-app-55d7b.firebasestorage.app',
    measurementId: 'G-8P0L0Q7LQ1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCg1G2bGegHdCNE9kv-2CZupnaMrzm_Fwo',
    appId: '1:39167277239:android:179084965f3d43f2cbb532',
    messagingSenderId: '39167277239',
    projectId: 'song-app-55d7b',
    storageBucket: 'song-app-55d7b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAzXG_BipN2Hl-Pz3pq7tQcF_e6EyeXivY',
    appId: '1:39167277239:ios:a7589e07b49491b8cbb532',
    messagingSenderId: '39167277239',
    projectId: 'song-app-55d7b',
    storageBucket: 'song-app-55d7b.firebasestorage.app',
    iosBundleId: 'com.example.dhun',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAzXG_BipN2Hl-Pz3pq7tQcF_e6EyeXivY',
    appId: '1:39167277239:ios:a7589e07b49491b8cbb532',
    messagingSenderId: '39167277239',
    projectId: 'song-app-55d7b',
    storageBucket: 'song-app-55d7b.firebasestorage.app',
    iosBundleId: 'com.example.dhun',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1m5jKBIa9Svz8PQgMcOpWf_KGMM1k2GI',
    appId: '1:39167277239:web:e73c4bd43bc2d48dcbb532',
    messagingSenderId: '39167277239',
    projectId: 'song-app-55d7b',
    authDomain: 'song-app-55d7b.firebaseapp.com',
    storageBucket: 'song-app-55d7b.firebasestorage.app',
    measurementId: 'G-FT8N3YM8YJ',
  );
}
